baseURL = ""
languageCode = "ja-jp"
title = "PriceWatch"
theme = "PaperMod"

[params]
  description = "Price tracking for various products."
  keywords = ["price", "tracking", "products"]
  

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
