[home]
  main_section = "posts"

[params]
  disableThemeToggle = true
  disableScrollToTop = true
  disableInlineCSS = true
  disableCodeBlockCopy = true
  disableBreadcrumb = true
  disableToc = true
  disableSearch = true
  disableComments = true
  disableShare = true
  disableSocial = true
  disableAuthor = true
  disableSitemap = true
  disableRobotsTXT = true
  disableOpenGraph = true
  disableTwitterCards = true
  disableSchema = true
  disableAnalytics = true
  disablePWA = true
  disableWebmanifest = true
  disableAssets = true
  disableCover = true
  disableFuseOpts = true
  disableSite = true
  disableHeader = true
  disableFooter = true
  disableDisqus = true
  disableUtterances = true
  disableGiscus = true
  disableGitment = true
  disableValine = true
  disableTwikoo = true
  disableWaline = true
  disableCactusComments = true
  disableRemark42 = true
  disableVssue = true
  disableArtalk = true
  disableLightGallery = true
  disableMapbox = true
  disableAlgolia = true
  disableSearch = true
  disableKofi = true
  disableBuymeacoffee = true
  disablePatreon = true
  disablePaypal = true
  disableAlipay = true
  disableWechatpay = true
  disableCustom = true
