name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  HUGO_VERSION: "0.124.1" # Specify Hugo version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (PaperMod)
          fetch-depth: 0 # Fetch all history for .GitInfo and auto-lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{ env.HUGO_VERSION }}'
          extended: true # Required for some themes like PaperMod

      - name: Build Hugo site
        run: hugo --minify --source site # Build from the 'site' directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/public # Upload the generated public directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
